### ISSUE TITLE
./forsyde-shell script for MacOSX opening a new terminal

### ISSUE THREAD

**Issue by joseedil** [forsyde/forsyde-shell#6]
This is caused by using "open -a Terminal.app" on the forsyde-shell script.

Is this the intended behavior?

Why not call directly the osx_runner script and let it run on the terminal emulator the user prefers (usually iTerm)?

Is this intended to be accessed from a Finder window?

**Comment by ugeorge** [comment]
Good point! To be honest, this implementation mirrors the behavior of the Linux version, which, as you figured out, opens *ONE* new terminal instance, with all the environment variables set up accordingly. This is mainly not to interfere with the normal experience or shell of the user (e.g. accidentally overwriting the environment for that session and such).

As my knowledge of MacOSX is very limited, I am more than happy for suggestions on "how to make it better".

**Comment by ingo-sander** [comment]
Please tell me, when it is stable enough, then I can also test it on my Mac. However, I have a bad internet connection here in Oldenburg.

**Comment by joseedil** [comment]
I'll try it on a raw OSX setup to see what happens.

**Comment by ugeorge** [comment]
@ingo-sander now it is stable. I believe we can make a snapshot for future reference, as a pre-release. It still does not include ForSyDe-Haskell tools, and the OSX version does not support `forsyde-m2m` due to some Java libraries dependencies (will be deprecated once DeSyDe API is finished so there is no point in spending effort on this). Apart from that, feel free to test the existing features.
